channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - altair=4.1.0
  - altair_data_server=0.4.1
  - altair_viewer=0.3.0
  - bioconductor-depmap=1.8.0
  - bioconductor-deseq2
  - bioconductor-experimenthub=2.2.0
  - bioconductor-fgsea
  - bowtie2
  - click=8.0.3
  - flask=2.0.2
  - gawk=5.1.0
  - ipykernel=6.5.0
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - json5=0.9.5
  - jupyter=1.0.0
  - jupyter_client=6.1.12
  - jupyter_console=6.4.0
  - jupyter_core=4.9.1
  - jupyter_server=1.11.2
  - mageck=0.5.9.4
  - matplotlib=3.5.0
  - natsort=8.0.0
  - nodejs
  - nbformat=4
  - numpy=1.19.1
  - pandas=1.1.3
  - pillow=8.4.0
  - pip=20.2.4
  - plotly=5.5.0
  - pyyaml=5.4.1
  - r-base=4.1.1
  - r-devtools
  - r-dplyr
  - r-forcats
  - r-ggplot2
  - r-ggpolypath
  - r-ggridges
  - r-magrittr
  - r-mixtools
  - r-nloptr
  - r-rcpp
  - r-readr
  - r-robustrankaggreg
  - r-stringi
  - r-statmod
  - r-sn
  - r-stringr
  - r-tibble
  - r-tidyr
  - r-venn
  - rpy2=3.4.5
  - samtools=1.14
  - scikit-learn=0.23.2
  - scipy=1.7.2
  - snakemake
  - statsmodels=0.13.0
  - tk=8.6.11
  - werkzeug=2.0.3
  - yaml=0.2.5
  - pip:
    - fastcluster==1.2.4
    - jsonschema==3.2.0
    - nest-asyncio==1.5.1
    - ipywidgets==8.0.0b0
    - jinja2==3.0.3
    
